### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by yiyunliu** [yiyunliu/liquidhaskell#1]
09/12/2019
- [x] Fix semigroup_desugared.hs 
- [x] List all the type classes in a module.  Add to GhcSrc a list of type classes named `gsTCls  :: [Class]`.
- [x] Source to Core renaming map with GHC. 
- [x] Core to Logic

**Comment by yiyunliu** [comment]
- [ ] refine $cmappend_a1ok

**Comment by yiyunliu** [comment]
- [ ] better error message when the method ordering is incorrect.
- [ ] generate refinement for methods. This [function](https://github.com/ucsd-progsys/liquidhaskell/blob/5af4f07495348637c3c15ea18588963e77d143e9/src/Language/Haskell/Liquid/Bare/Class.hs#L46) is somehow related.
- [ ] elaboration using GHC API. Directly parsing the terms can be problematic due to type aliasing. 
- [ ] dictionaries that need to be dropped: Fractional, Num, Eq, Ord ... Anything related to BinOp from liquid-fixpoint. This shouldn't be needed in the future if we change liquid-fixpoint accordingly.
